/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PeriodService } from "../period.service";
import { PeriodCreateInput } from "./PeriodCreateInput";
import { Period } from "./Period";
import { PeriodFindManyArgs } from "./PeriodFindManyArgs";
import { PeriodWhereUniqueInput } from "./PeriodWhereUniqueInput";
import { PeriodUpdateInput } from "./PeriodUpdateInput";

export class PeriodControllerBase {
  constructor(protected readonly service: PeriodService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Period })
  async createPeriod(@common.Body() data: PeriodCreateInput): Promise<Period> {
    return await this.service.createPeriod({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startDate: true,
        endDate: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Period] })
  @ApiNestedQuery(PeriodFindManyArgs)
  async periods(@common.Req() request: Request): Promise<Period[]> {
    const args = plainToClass(PeriodFindManyArgs, request.query);
    return this.service.periods({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startDate: true,
        endDate: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Period })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async period(
    @common.Param() params: PeriodWhereUniqueInput
  ): Promise<Period | null> {
    const result = await this.service.period({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startDate: true,
        endDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Period })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePeriod(
    @common.Param() params: PeriodWhereUniqueInput,
    @common.Body() data: PeriodUpdateInput
  ): Promise<Period | null> {
    try {
      return await this.service.updatePeriod({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          startDate: true,
          endDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Period })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePeriod(
    @common.Param() params: PeriodWhereUniqueInput
  ): Promise<Period | null> {
    try {
      return await this.service.deletePeriod({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          startDate: true,
          endDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
